<script src="{{ asset('themes/metricaladmin/assets/plugins/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/jquery-ui/jquery-ui.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/popper/popper.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/feather-icon/feather.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/pace/pace.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/toastr/toastr.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/countup/counterup.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/waypoints/waypoints.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/chartjs/chartjs.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/apex-chart/apexcharts.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/apex-chart/irregular-data-series.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/plugins/simpler-sidebar/jquery.simpler-sidebar.min.js') }}"></script>

<script src="{{ asset('themes/metricaladmin/assets/js/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/js/highlight.min.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/js/app.js') }}"></script>
<script src="{{ asset('themes/metricaladmin/assets/js/custom.js') }}"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
{{--<script src="https://code.highcharts.com/modules/exporting.js"></script>--}}
{{--<script src="https://code.highcharts.com/modules/offline-exporting.js"></script>--}}
